# Hyprland start up application
exec-once = waybar &
exec-once = hyprpaper &
exec-once = mako
exec-once = fcitx5
exec-once = echo "Xft.dpi: 140" | xrdb -merge
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
