# window float
windowrulev2 = float,class:^(thunar)$
windowrulev2 = float,class:^(imv)$
windowrulev2 = float,class:^(mpv)$

# window size
windowrulev2 = size 1280 720,class:^(thunar)$

# window center
windowrulev2 = center,class:^(thunar)$

# no window border
# windowrulev2 = noborder,class:^(librewolf)$
# windowrulev2 = noborder,class:^(mpv)$
