# Shell
# shell fish

# Font
font_family JetBrainsMono Nerd Font Mono
font_size 19
# disable_ligatures always

# Background
# gles2
background_opacity 0.83

# vulkan
# background_opacity 0.95

# Include pywal colors
include $HOME/.cache/wal/colors-kitty.conf
