[FileDialog]
history=file:///home/hz/Pictures/wallpaper, file:///home/hz/Videos/NSFW/Swing Out Sisters, file:///home/hz/Downloads, file:///home/hz/Videos, file:///home/hz/Downloads/Torrents
lastVisited=file:///home/hz/Videos
qtVersion=6.8.1
shortcuts=file:, file:///home/hz
sidebarWidth=121
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3\xbf\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x2\xe8\0\0\0\x1\0\0\0\0\0\0\0\x37\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x63\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)"
viewMode=Detail
