#!/usr/bin/sh
# @author nate zhou
# @since 2025
# update i3blocks-mpd module whenever mpd playing status changes

# in `i3blocks/config`:
#[mpdd]
#command= i3blocks-mpdd
## -2 will respawn the command as soon as it terminates
#interval=-2

pid="${HOME}/.config/mpd/mpd.pid"

if [ -f "$pid" ] ; then
    pkill -SIGRTMIN+8 i3blocks && mpc idle >/dev/null && pkill -SIGRTMIN+8 i3blocks || break
else
	exit
fi
