#!/usr/bin/env bash

# pywal16
if [[ -f "$HOME/.cache/wal/colors.sh" ]]; then
    source "$HOME/.cache/wal/colors.sh"
    color="$color6"
else
    color=""
fi

count=$(descratch | wc -l)

if [[ "$count" =~ ^[0-9]+$ ]] && (( count > 0 )); then
    if [[ -n "$color" ]]; then
        printf "<span foreground='%s'>   %s</span>\n" "$color" "$count"
    else
        printf "   %s\n" "$count"
    fi
fi
