require("config/main/main")
require("config/modes/viewer/config")
require("config/modes/viewer/bindings")
require("config/modes/gallery/config")
require("config/modes/gallery/bindings")
require("config/modes/slideshow/config")
